[package]
name = "morphorm"
version = "0.4.0"
edition = "2018"
author = "George Atkinson"
license = "MIT"
description = "A UI layout engine"
repository = "https://github.com/geom3trik/morphorm"
keywords = ["ui", "gui", "layout"]


[dependencies]
smallvec = "1.6.1"
bitflags = "1.3.1"

[dev-dependencies]
morphorm-ecs = {path = "ecs"}
winit = { version = "0.25.0", default-features = false }
femtovg = {version = "0.4.0", default-features = false}
glutin = "0.27.0"
rand = "0.8.4"

[lib]
doctest = false