[package]
name = "morphorm-ecs"
version = "0.1.0"
edition = "2018"
description = "A mini ECS used for testing the morphorm crate."
license = "MIT"

[dependencies]
morphorm = {version = "0.4.0", path = "../"}
rand = "0.8.4"