[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
# vizia = {path = "../../vizia"}
vizia = {git = "https://github.com/vizia/vizia"}
morphorm-ecs = {path = "../ecs"}
morphorm = {path = ".."}
slotmap = "1.0.6"